# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180328_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criterions',
            new_name='Element',
        ),
        migrations.RenameModel(
            old_name='Farmerscores',
            new_name='Farmerscore',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='criterionID',
            new_name='elementID',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='criterion_text',
            new_name='element_text',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='criterion_weight',
            new_name='element_weight',
        ),
    ]
