# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180404_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('Name', models.CharField(max_length=40)),
                ('Location', models.CharField(max_length=40)),
                ('Region', models.CharField(max_length=40)),
                ('Country', models.CharField(max_length=40)),
            ],
        ),
    ]
