# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_b_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('B1', models.IntegerField()),
                ('B2', models.IntegerField()),
                ('B3', models.IntegerField()),
                ('B4', models.IntegerField()),
                ('B5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_c_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('C1', models.IntegerField()),
                ('C2', models.IntegerField()),
                ('C3', models.IntegerField()),
                ('C4', models.IntegerField()),
                ('C5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_d_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('D1', models.IntegerField()),
                ('D2', models.IntegerField()),
                ('D3', models.IntegerField()),
                ('D4', models.IntegerField()),
                ('D5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_e_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('E1', models.IntegerField()),
                ('E2', models.IntegerField()),
                ('E3', models.IntegerField()),
                ('E4', models.IntegerField()),
                ('E5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_f_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('F1', models.IntegerField()),
                ('F2', models.IntegerField()),
                ('F3', models.IntegerField()),
                ('F4', models.IntegerField()),
                ('F5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_g_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=4)),
                ('G1', models.IntegerField()),
                ('G2', models.IntegerField()),
                ('G3', models.IntegerField()),
                ('G4', models.IntegerField()),
                ('G5', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Farmerscore',
            new_name='Farmer_a_score',
        ),
    ]
