# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180405_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementID', models.CharField(max_length=3)),
                ('element_weight', models.IntegerField()),
                ('element_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Element_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementID', models.CharField(max_length=3)),
                ('element_weight', models.IntegerField()),
                ('element_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Element_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementID', models.CharField(max_length=3)),
                ('element_weight', models.IntegerField()),
                ('element_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Element_e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementID', models.CharField(max_length=3)),
                ('element_weight', models.IntegerField()),
                ('element_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Element_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementID', models.CharField(max_length=3)),
                ('element_weight', models.IntegerField()),
                ('element_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Element_g',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementID', models.CharField(max_length=3)),
                ('element_weight', models.IntegerField()),
                ('element_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Element',
            new_name='Element_a',
        ),
    ]
