# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180405_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element_e',
            new_name='a_Element',
        ),
        migrations.RenameModel(
            old_name='Element_f',
            new_name='b_Element',
        ),
        migrations.DeleteModel(
            name='Element_a',
        ),
        migrations.DeleteModel(
            name='Element_b',
        ),
        migrations.DeleteModel(
            name='Element_c',
        ),
        migrations.DeleteModel(
            name='Element_d',
        ),
        migrations.DeleteModel(
            name='Element_g',
        ),
        migrations.DeleteModel(
            name='Farmer_c_score',
        ),
        migrations.DeleteModel(
            name='Farmer_d_score',
        ),
        migrations.DeleteModel(
            name='Farmer_e_score',
        ),
        migrations.DeleteModel(
            name='Farmer_f_score',
        ),
        migrations.DeleteModel(
            name='Farmer_g_score',
        ),
    ]
