# Generated by Django 2.2.1 on 2019-06-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180519_0541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashsboardscores',
        ),
    ]
